"""empty message

Revision ID: 0631c434c6bf
Revises: f0ec7e764826
Create Date: 2020-05-23 17:24:08.367139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0631c434c6bf'
down_revision = 'f0ec7e764826'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('changed', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'changed')
    # ### end Alembic commands ###
