"""empty message

Revision ID: 325ce4ccbabe
Revises: a3be1e5daa74
Create Date: 2019-10-08 19:12:40.169488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '325ce4ccbabe'
down_revision = 'a3be1e5daa74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_verified')
    # ### end Alembic commands ###
