"""empty message

Revision ID: e337e630fac2
Revises: dbbc0d99f48d
Create Date: 2020-05-01 00:53:17.898582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e337e630fac2'
down_revision = 'dbbc0d99f48d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temp_email_change', sa.Column('otp_expiration', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('temp_email_change', 'otp_expiration')
    # ### end Alembic commands ###
